name: Ubuntu Release

on: 
  push:
    tags:
      - "v*-ubuntu*"

jobs:
  ubuntu_release:
    name: Ubuntu Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Ubuntu ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Build Ubuntu
        run: cmake . && make
      - name: Upload liborthanc_gcp_storage_plugin.so
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin/liborthanc_gcp_storage_plugin.so
          asset_name: liborthanc_gcp_storage_plugin.so
          asset_content_type: "application/octet-stream"